language: java
sudo: required
jdk: oraclejdk8

services:
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=anhtv08/spring-boot-with-fargate
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  - provider: s3
    # rest of S3 deployment for MyApp.zip
    # ⋮
  - provider: codedeploy
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: "S3 Bucket"
    key: latest/MyApp.zip
    application: MyApp
    deployment_group: MyDeploymentGroup